# Generated by Django 6.0.3 on 2026-04-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('razorpay_id', models.CharField(max_length=30)),
                ('payment_stayus', models.BooleanField(default=False)),
            ],
        ),
    ]
