# Generated by Django 6.0.3 on 2026-04-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_stayus',
            new_name='payment_status',
        ),
    ]
